{
    task : charades,
    paths: {
        ckpt_dir: ./ckpt,
        cache_dir : ./data_pkl/,
        feature_path: /path/charades/feat/i3d_v1,
        glove_path: /path/glove/glove.840B.300d.txt,
        train_path: ./data/charades_gt/train.json,
        test_path: ./data/charades_gt/test.json,
        val_path: 
    },
  train: {
    epochs: 100,
    batch_size: 16,
    lr: 0.0001,
    clip_norm: 1.0
  },
  model: {
        name: MultiTeacherEnsemble,
        max_vlen: 64,
        max_tlen: 20,
        vdim: 1024,
        dim: 128,
        num_heads: 8,
        word_dim: 300,
        char_dim: 100,
        droprate: 0.4,
        attn_layer: 2,
    },
    loss:
    {   match_lambda: 1.0, 
        tau: 0.3,
        no_gumbel: true,

        label_kdfunc: kdfunc_KL,
        label_cof: 0.1,
        label_temperature: 1.0,

        t0_path: ./results/charades_SeqPAN_train_logits.pkl,
        t1_path: ./results/charades_EMAT_train_logits.pkl,
        t2_path: ./results/charades_BAN_train_logits.pkl,
    }
}